version: '3.8'

services:
  httpd:
    image: httpd:latest
    ports:
      - "8080:8080"
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./index.html:/usr/local/apache2/htdocs/index.html
    depends_on:
      - wp
  db:
    image: mariadb:latest
    restart: on-failure
    environment:
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress
      MARIADB_ROOT_PASSWORD: wordpress
      MARIADB_DATABASE: wordpress
      
  wp:
    depends_on:
    - db
    image: wordpress:latest
    volumes:
    - ./wp:/var/www/html
    - ./vulnerable-plugin:/var/www/html/wp-content/plugins/vulnerable-plugin
    ports:
    - 5000:80
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress